### ISSUE TITLE
Error: One or more errors occurred. (Value cannot be null. (Parameter 'source'))

### ISSUE THREAD

**Issue by Lastnet0709** [glad-tidings/SeedBot#1]
![image](https://github.com/user-attachments/assets/f0b9ed9d-f63e-43cd-871d-4471e7dc4eca)

**Comment by glad-tidings** [comment]
enter query_id in data.txt file

**Comment by Lastnet0709** [comment]
![image](https://github.com/user-attachments/assets/6178a8da-ad1c-49f4-a245-1198601a2a8b)

**Comment by glad-tidings** [comment]
use new version
