### ISSUE TITLE
Synced failed on startup

### ISSUE THREAD

**Issue by Dimitrius1** [glad-tidings/SeedBot#2]
[Seed] [1] get profile data failed
[Seed] [1] sync sleep '4h 45m 8s'
It's in last version, same problem was in bums. thx.

**Comment by glad-tidings** [comment]
Enter all account phone number and api_id and api_hash in data.txt file and run bot and for first time choose 2.create session when all sessions created run bot again and choose 1.run bot

**Comment by glad-tidings** [comment]
for bums use new version (v2.4)

**Comment by Dimitrius1** [comment]
Yes, bums now working fine. But in SeedBot v1.3 have error after starting bot with session:
[Seed] [1] get profile data failed
[Seed] [1] sync sleep '2h 56m 1s'

**Comment by glad-tidings** [comment]
fix get profile data failed
use new version (v1.4)
